admin_facing/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .apiviews import AppApi, TaskCreateApi

app_name = "admin_facing"

urlpatterns = [
    path("home/", views.user_home_view, name="home"),
    path("category/", views.app_view, name="app"),
    path("task_create/<int:app_id>/", views.task_create, name="task_create"),
    path("task_claimed/", views.task_claimed, name="task_claimed"),
    path("task_claimed_list/", views.user_claimed_task_list, name="task_claimed_list"),
    path("appdata/", AppApi.as_view(), name="app"),
    path("taskcreated/<int:app_id>/", TaskCreateApi.as_view(), name="taskcreate"),
]

reward/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("user_facing.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("user_facing/", include("django.contrib.auth.urls")),
    path("admin_facing/", include("admin_facing.urls")),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
]

admin_facing/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from uuid import uuid4

# application create serializer
class Application(models.Model):
    Socialmedia = "Socialmedia"
    Heatlhmanagement = "HealthManagement"
    Entertainment = "Entertainment"
    Educational = "Educational"
    Productivity = "Productivity"
    Lifestyle = "Lifestyle"
    FIELD_IN_CATEGORY_CHOICES = [
        (Socialmedia, "Socialmedia"),
        (Heatlhmanagement, "Heatlhmanagement"),
        (Entertainment, "Entertainment"),
        (Educational, " Educational"),
        (Productivity, "Productivity"),
        (Lifestyle, "Lifestyle"),
    ]
    category = models.CharField(
        max_length=200,
        choices=FIELD_IN_CATEGORY_CHOICES,
        default=Socialmedia,
    )

    name = models.CharField(max_length=200)
    points = models.IntegerField()



class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    application = models.ForeignKey(Application, on_delete=models.CASCADE)
    image = models.ImageField()

admin_facing/forms.py
from django import forms

from .models import Application, Task


class AppForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = (
            "category",
            "name",
            "points",
        )


class AppList(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["image"]


"""class AppDownloaded(forms.ModelForm):
    class Meta:
        model = App_list
        fields = (
            "Appname",
            "Points",
            "app_download",
        )
"""

admin_facing/views.py
from django.shortcuts import render, redirect, reverse
from .models import Application, Task
from .forms import AppForm, AppList
from django.core.files.storage import FileSystemStorage
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.


@staff_member_required
def app_view(request):
    if request.method == "POST":
        form = AppForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse("admin_facing:home"))

    else:
        form = AppForm()
    context = {"form": form}
    return render(request, "admin_facing/app.html", context)


@login_required
def task_create(request, app_id):
    app = Application.objects.get(id=app_id)
    if request.method == "POST":
        # app_id = request.kwargs.get("app_id")
        form = AppList(request.POST, request.FILES)
        if form.is_valid():
            img = form.cleaned_data["image"]
            fs = FileSystemStorage()
            image = fs.save(img.name, img)
            qs = Task.objects.filter(user=request.user, application=app)
            if qs.exists():
                messages.warning(request, "user already exists.")
                return redirect(reverse("admin_facing:home"))
            task = Task.objects.create(user=request.user, application=app, image=image)
            return redirect(reverse("admin_facing:task_claimed"))
    else:
        form = AppList()
    context = {"form": form, "app": app}
    return render(request, "admin_facing/app_list.html", context)


def user_home_view(request):
    app = Application.objects.all()
    context = {"app": app}
    return render(request, "admin_facing/task_create.html", context)


@login_required
def task_claimed(request):
    user = request.user
    tasks = Task.objects.filter(user=user)
    points = 0
    for task in tasks:
        points += task.application.points
    context = {"points": points, "tasks": tasks}
    return render(request, "admin_facing/task_claimed.html", context)


@login_required
def user_claimed_task_list(request):
    user = request.user
    tasks = Task.objects.filter(user=user)
    context = {"tasks": tasks}
    return render(request, "admin_facing/task_claimed_list.html", context)

admin_facing/templates/admin_facing/app.html
{% block content %}
<form method="Post" class="post-form">{% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='save' />
</form>
{% endblock %}

admin_facing/templates/admin_facing/app_downloaded.html
{% for app in downloaded_app %}
{% csrf_token %}
appname:{{ app.Appname }}<br>
points:{{ app.Points }}<br>
downloadedapp:{{ app.app_download }}<br>
{% endfor %}

admin_facing/templates/admin_facing/app_list.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
appname:{{ app.name }}<br>
points:{{ app.points }}<br>
<form method="POST" action="{% url 'admin_facing:task_create' app.id %}" enctype="multipart/form-data"
    class="post-form">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"> <br>
</form>

admin_facing/templates/admin_facing/task_claimed.html
{% csrf_token %}
user:{{ user }}<br>
points:{{ points }}<br>

admin_facing/templates/admin_facing/task_claimed_list.html
{% for task in tasks %}
username:{{ task.user }}<br>
appnamae:{{task.application.name}}<br>
points:{{ task.application.points }}<br>
{% endfor %}

admin_facing/templates/admin_facing/task_create.html
<a href="{% url 'login' %}">login</a><br>
<a href="{% url 'logout' %}">logout</a><br>
<a href="{% url 'profile' %}">userprofile</a><br>
<a href="{% url 'admin_facing:task_claimed' %}">userpoints</a><br>

{% for application in app %}
{% csrf_token %}
appname:{{ application.name }}<br>
points:{{ application.points }}<br>
<a href="{% url 'admin_facing:task_create' application.id %}">{{ application.name }}</a><br>
{% endfor %}